name: Publish latest code to server
on:
  push:
    branches:
      - production
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Ferret
            echo "Stopping server"
            pkill node || true
            echo "Pulling latest"
            git pull
            echo "Starting server"
            npm install
            cd src
            cd run
            git log --pretty=format:'%h' -n 1 > hash.txt
            cd ..
            nohup node main > run/latest.log 2>&1 &
            echo "Started server, action complete!"
            exit
